#version: '2'
#
#services:
#
#  db:
#    container_name: douzone_compose
#    image: postgres:latest
#    restart: always
#    volumes:
#      - /var/lib/docker/volumes/4dafdb5bcc019e3d7aee16279ba4f22f0d0632678e8924c4fa8ca746b7a50cba/_data
#    environment:
#      POSTGRES_DB: douzone
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: postgres123
#      HOST: localhost
#      PORT: 5432
#      PGDATA: /var/lib/postgres/data/pgdata


version: "3"
services:
  postgresql:
    image: postgres:latest
    restart: always
    container_name: douzone_compose
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: douzone
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - ./data/postgres/:/var/lib/postgres/data/pgdata
