version: '2'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: project_name
      POSTGRES_PASSWORD: db_password
      PGDATA: /var/lib/postgres/data/pgdata
